### ISSUE TITLE
st-flash cannot work in .py file

### ISSUE THREAD

**Issue by Catherinecyj** [mupq/pqm4#233]
My board: STM32F407G-DISC1
OS: Linux (Ubuntu 18.04)

I tried `python3 benchmarks.py` to get the benchamrks of the implementations but it returns:

> make: 'bin/crypto_kem_saber_m4fspeed_stack.bin' is up to date.
Traceback (most recent call last):
  File "benchmarks.py", line 15, in <module>
    test.test_all(schemes)
  File "/home/magnolia/Desktop/kyber_saber/mupq/mupq.py", line 202, in test_all
    if self.run_test(implementation) == -1:
  File "/home/magnolia/Desktop/kyber_saber/mupq/mupq.py", line 245, in run_test
    output = super().run_test(implementation)
  File "/home/magnolia/Desktop/kyber_saber/mupq/mupq.py", line 193, in run_test
    return self.interface.run(binary)
  File "/home/magnolia/Desktop/kyber_saber/mupq/platforms.py", line 71, in run
    self.flash(binary_path)
  File "/home/magnolia/Desktop/kyber_saber/mupq/platforms.py", line 116, in flash
    stderr=subprocess.DEVNULL,
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['st-flash', '--reset', 'write', 'bin/crypto_kem_saber_m4fspeed_stack.bin', '0x8000000']' returned non-zero exit status 255.

Also, I tried with `st-flash write bin/crypto_kem_saber_m4fspeed_stack.bin 0x8000000 ` and it returns:

> st-flash 1.7.0-186-gc4762e6
/usr/local/stlink/chips: No such file or directory
2022-04-22T11:08:27 WARN common.c: unknown chip id! 0x413
Failed to connect to target

I can use STM32 ST-LINK Utility to flash the .bin file to my STM32F407G-DISC1 and get the result from board, I just cannot run these .py file.

**Comment by mkannwischer** [comment]
Did you manage to make it work by now? Let me know what the problem was if you did. 
I'll close this as it seems unrelated to pqm4.
