### ISSUE TITLE
testvectors.py seems to timeout but does not recover like test.py

### ISSUE THREAD

**Issue by technotive** [mupq/pqm4#9]
First to confirm that flashign works, and to get an idea of the speed at which a  test runs, I ran `sudo python3 test.py kyber768`
Which outputs:
```
Flashing bin/crypto_kem_kyber768_ref_test.bin..
Flashed, now running tests...
  .. found output marker..
Testing if tests were successful..
passed.
Flashing bin/crypto_kem_kyber768_m4_test.bin..
Flashed, now running tests...
timed out while waiting for the markers
Flashing bin/crypto_kem_kyber768_m4_test.bin..
Flashed, now running tests...
  .. found output marker..
Testing if tests were successful..
passed.
```

Having an idea about the speed, I decided to run `sudo python3 testvectors.py kyber768`
The first time it ran for over 10 minutes and then I decided it had probably hung and interrupted it:
```
This script flashes the test vector binaries onto the board, and then
 writes the resulting output to the testvectors directory. It then
 checks if these are internally consistent and match the test vectors
 when running the reference code locally.
Flashing bin/crypto_kem_kyber768_m4_testvectors.bin..
Flashed, now computing test vectors..
^CTraceback (most recent call last):
  File "testvectors.py", line 54, in <module>
    x = dev.read()
  File "/home/nevernown/.local/lib/python3.5/site-packages/serial/serialposix.py", line 483, in read
    ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())
KeyboardInterrupt
```
Sure enough the second run almost immediately got results, which makes my suspicion grow that it indeed hung:
```
This script flashes the test vector binaries onto the board, and then
 writes the resulting output to the testvectors directory. It then
 checks if these are internally consistent and match the test vectors
 when running the reference code locally.
Flashing bin/crypto_kem_kyber768_m4_testvectors.bin..
Flashed, now computing test vectors..
  .. found output marker..
  .. wrote test vectors!
Flashing bin/crypto_kem_kyber768_ref_testvectors.bin..
Flashed, now computing test vectors..
  .. found output marker..
```
But this run stops after finding the second output marker (It's been stuck at the above output for about 6 minutes now).

My question is twofold: 1. Did it really hang? 2. How can I have more verbose output on what is going on?

**Comment by technotive** [comment]
I'm not too familiar with the inner workings yet, but after some tests it seems like that sometimes something goes wrong after finding output markers. Even after checking for successful flashing and successfully finding an output marker.
There seems to be zero feedback about if something went wrong or what went wrong in this case. Because it could just be that sphincs costs about an hour to run.
